spring:
  application:
    name: jungle-article
  #  profiles: docker
  #  profiles:
  #    active: dev

  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elastic-search
#  rabbitmq:
#    host: 192.168.176.130
#    port: 5672
#    username: root
#    password: root
#without config
server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/